[package]
name = "remote_cam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
jni = { version="*", default-features = false}


[dependencies.rcmd-suit]
path = "../rcmd-suit"
default-features = false